### ISSUE TITLE
Unable to build client.exe. running windows 11

### ISSUE THREAD

**Issue by Ragekill3377** [moom825/Discord-RAT-2.0#78]
![discord-not-work](https://github.com/moom825/Discord-RAT-2.0/assets/147400816/bdee24d6-5ba6-4960-a381-482e53dfa758)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: Could not open file C:\Users\Moiz\Downloads\release\Release\Discord rat.exe for reading. Error: 00000002
   at dnlib.IO.MemoryMappedDataReaderFactory.Windows.Mmap(MemoryMappedDataReaderFactory creator, Boolean mapAsImage)
   at dnlib.IO.MemoryMappedDataReaderFactory.CreateWindows(String filename, Boolean mapAsImage)
   at dnlib.IO.DataReaderFactoryFactory.CreateDataReaderFactory(String fileName, Boolean mapAsImage)
   at dnlib.IO.DataReaderFactoryFactory.Create(String fileName, Boolean mapAsImage)
   at dnlib.PE.PEImage..ctor(String filename, Boolean mapAsImage, Boolean verify)
   at dnlib.DotNet.MD.MetadataFactory.Load(String fileName, CLRRuntimeReaderKind runtime)
   at dnlib.DotNet.ModuleDefMD.Load(String fileName, ModuleCreationOptions options)
   at dnlib.DotNet.AssemblyDef.Load(String fileName, ModuleCreationOptions options)
   at builder.Form1.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
builder
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Moiz/Downloads/release/builder.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    
     error 00000002 could not access file. windows 11 x64 intel core i3

**Comment by HeroNootRoot** [comment]
i think its because you open it but the name of it its with space

**Comment by collingames101** [comment]
how do we fix that i got it too

**Comment by Oxl-Legacy** [comment]
same error windows 10

**Comment by Ragekill3377** [comment]
> i think its because you open it but the name of it its with space

Nope I wrote it properly still getting an error... @moom825 Please check this

**Comment by Ragekill3377** [comment]
@Oxl-Legacy @collingames101 Wait try disabling AntiVirus & check I am Not using this anymore.
